### ISSUE TITLE
Update button under edit keeps spinning

### ISSUE THREAD

**Issue by webbertakken** [wurde/themebuilder#5]
I don't know what's proper behaviour but the update button didn't seem to work when i added some styles.

Steps to reproduce:

- Clean install according to [README.md](README.md)
- Start the application
- Click on "Edit"
- Add sass variable "$white: green"
- Click "Update"

Expected behaviour

- Some description above the edit field as of what to put in there.
- It would stop spinning and get me to the recompiled styles.

Actual behaviour

- It kept spinning and didn't give any feedback.
- The styles stayed the same.
- I was unable to find an error log.

**Comment by wurde** [comment]
I've reproduced the error and will begin to find a solution. Sorry for the delay.

**Comment by wurde** [comment]
With version 2.0.1 the "Update" button will now render either an error (if unexpected syntax or variables) or more likely in your case render successfully. The problem came from Bootstrap 4.0 removing the _custom.scss file. There is an added dependency now of `npm install -g sass`. I'd recommend a fresh install to get working.
